# Generated by Django 3.2.7 on 2021-09-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64, verbose_name='Event')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('region', models.CharField(max_length=16, verbose_name='Region')),
                ('netplay', models.BooleanField(verbose_name='Netplay')),
                ('version', models.CharField(max_length=64, verbose_name='Version')),
                ('p1name', models.CharField(max_length=32, verbose_name='P1Name')),
                ('p1char1', models.CharField(max_length=4, verbose_name='P1Char1')),
                ('p1char2', models.CharField(max_length=4, verbose_name='P1Char2')),
                ('p1char3', models.CharField(max_length=4, verbose_name='P1Char3')),
                ('p2name', models.CharField(max_length=32, verbose_name='P2Name')),
                ('p2char1', models.CharField(max_length=4, verbose_name='P2Char1')),
                ('p2char2', models.CharField(max_length=4, verbose_name='P2Char2')),
                ('p2char3', models.CharField(max_length=4, verbose_name='P2Char3')),
                ('url', models.CharField(max_length=256, verbose_name='URL')),
            ],
        ),
    ]
