# Generated by Django 3.2.7 on 2021-09-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vod',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
